ncrowds-workspace/modules/com.ncrowd.scrum.portlet/src/main/java/com/ncrowd/scrum/bean/DocumentBean.java
package com.ncrowd.scrum.bean;

import com.liferay.document.library.kernel.exception.DuplicateFileException;
import com.liferay.document.library.kernel.exception.NoSuchFolderException;
import com.liferay.document.library.kernel.model.DLFileEntry;
import com.liferay.document.library.kernel.model.DLFileShortcut;
import com.liferay.document.library.kernel.model.DLFileVersion;
import com.liferay.document.library.kernel.util.DLUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.UserGroup;
import com.liferay.portal.kernel.repository.model.FileEntry;
import com.liferay.portal.kernel.repository.model.FileVersion;
import com.liferay.portal.kernel.repository.model.Folder;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.theme.ThemeDisplay;
import com.liferay.portal.kernel.util.FileUtil;
import com.ncrowd.model.DocumentMapping;
import com.ncrowd.model.Task;
import com.ncrowd.scrum.model.Document;
import com.ncrowd.scrum.model.TempFile;
import com.ncrowd.scrum.util.FacesMessageUtil;
import com.ncrowd.scrum.util.ScrumUtil;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.TreeNode;
import org.primefaces.model.UploadedFile;

@ManagedBean(name = "documentBean")
@ViewScoped
public class DocumentBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@ManagedProperty("#{editTaskBean}")
	private EditTaskBean editTaskBean;

	@ManagedProperty("#{prefBean}")
	private PreferencesBean prefBean;
	private transient TempFile fileToReplace;
	private static final String SCRUM_FOLDER_NAME = "ScrumPortlet";
	private static final Log LOG = LogFactoryUtil.getLog(DocumentBean.class);
	private long taskId;
	private long teamFolderId;
	private transient List<Document> documents;
	@ManagedProperty("#{trackerBean}")
	private ServiceTrackerBean serviceTrackerBean;

	public void setEditTaskBean(EditTaskBean editTaskBean) {
		this.editTaskBean = editTaskBean;
	}

	public void setPrefBean(PreferencesBean prefBean) {
		this.prefBean = prefBean;
	}

	public void setServiceTrackerBean(ServiceTrackerBean serviceTrackerBean) {
		this.serviceTrackerBean = serviceTrackerBean;
	}

	
	@PostConstruct
	public void init() {
		fileToReplace = null;
		Task task = editTaskBean.getCurrentTask();
		if (task != null) {
			taskId = task.getTaskId();
			loadTaskDocuments();
		} else {
			documents = new ArrayList<>();
		}

		try {
			checkDLFolders();
		} catch (Exception var3) {
			LOG.error("Error checking for scrum DLFolders", var3);
		}

	}

	@PreDestroy
	public void destroy() {
		if (fileToReplace != null) {
			try {
				fileToReplace.getFile().delete();
			} catch (Exception e) {
				LOG.error("Exception occurs : "+e);
			}
		}

	}

	public TempFile getFileToReplace() {
		return fileToReplace;
	}

	public void setFileToReplace(TempFile fileToReplace) {
		if (fileToReplace != null) {
			try {
				this.fileToReplace.getFile().delete();
			} catch (Exception var3) {
				LOG.error("Error deleting temp file", var3);
			}
		}

		this.fileToReplace = fileToReplace;
	}

	private void loadTaskDocuments() {
		documents = new ArrayList<>();

		try {
			List<DocumentMapping> mappings = serviceTrackerBean.getDocumentService().findByTaskId(taskId);
			for (DocumentMapping mapping : mappings) {
				addDocument(mapping.getMappingId(), mapping.getDlFileEntryId());
			}
		} catch (SystemException var4) {
			LOG.error("Error getting document mappings of task " + taskId, var4);
		}

	}

	private void addDocument(long mappingId, long fileEntryId) {
		try {
			DLFileEntry dlFileEntry = serviceTrackerBean.getDlFileService().fetchDLFileEntry(fileEntryId);
			if (dlFileEntry == null) {
				LOG.debug("DLFileEntry " + fileEntryId + " not found. Deleting mapping " + mappingId);
				deleteMapping(mappingId);
				return;
			}

			ThemeDisplay themeDisplay = ScrumUtil.getThemeDisplay();
			Document document = convertDLFileEntryToDocument(dlFileEntry, themeDisplay, mappingId);
			if (document != null) {
				documents.add(document);
			}
		} catch (SystemException var8) {
			LOG.error("Error getting DLFileEntry " + fileEntryId, var8);
		}

	}

	private Document convertDLFileEntryToDocument(DLFileEntry dlFileEntry, ThemeDisplay themeDisplay, long mappingId) {
		String thumbnailSrc = getThumbnailSrc(dlFileEntry, themeDisplay);
		String previewSrc = getPreviewURL(dlFileEntry, themeDisplay);
		Document document = new Document(dlFileEntry, thumbnailSrc, previewSrc, mappingId);
		document.setOldVersions(getOldDocumentVersions(dlFileEntry, themeDisplay));
		return document;
	}
	
	public StreamedContent getFile(long documentId,String title,String mimeType) throws PortalException, IOException {
		DLFileEntry dlFileEntry = serviceTrackerBean.getDlFileService().fetchDLFileEntry(documentId);
		if (dlFileEntry != null) {
			InputStream stream = dlFileEntry.getContentStream();
			ScrumUtil.writeStreamToOutputStream(stream,title, mimeType);
		}

		return null;
	}

	private List<Document> getOldDocumentVersions(DLFileEntry dlFileEntry, ThemeDisplay themeDisplay) {
		List<Document> oldVersions = new ArrayList<>();

		try {
			List<DLFileVersion> dlFileVersions = dlFileEntry.getFileVersions(-1);
			for (DLFileVersion version : dlFileVersions) {
				if (!version.getVersion().equals(dlFileEntry.getVersion())) {
					String thumbnailSrc = getThumbnailSrc(dlFileEntry, version, themeDisplay);
					String previewSrc = getPreviewURL(dlFileEntry, version, themeDisplay);
					oldVersions.add(new Document(version, thumbnailSrc, previewSrc));
				}
			}
		} catch (SystemException var9) {
			LOG.error("Error getting versions of DLFileEntry " + dlFileEntry.getFileEntryId(), var9);
		}

		return oldVersions;
	}

	public void deleteMapping(long mappingId) {
		try {
			serviceTrackerBean.getDocumentService().deleteDocumentMapping(mappingId);
		} catch (Exception var4) {
			LOG.error("Error deleting document mapping " + mappingId, var4);
		}

	}

	public List<Document> getDocuments() {
		return documents;
	}

	public void setDocuments(List<Document> documents) {
		this.documents = documents;
	}

	public TreeNode getDocumentTree() {
		TreeNode rootNode = new DefaultTreeNode("root", (TreeNode) null);
		Iterator var3 = this.documents.iterator();

		while (var3.hasNext()) {
			Document document = (Document) var3.next();
			TreeNode documentNode = new DefaultTreeNode(document, rootNode);
			documentNode.setExpanded(true);
			Iterator var6 = document.getOldVersions().iterator();

			while (var6.hasNext()) {
				Document oldVersion = (Document) var6.next();
				new DefaultTreeNode(oldVersion, documentNode);
			}
		}

		return rootNode;
	}

	private String getThumbnailSrc(DLFileEntry dlFileEntry, ThemeDisplay themeDisplay) {
		try {
			DLFileVersion dlFileVersion = dlFileEntry.getFileVersion();
			return this.getThumbnailSrc(dlFileEntry, dlFileVersion, themeDisplay);
		} catch (Exception var4) {
			LOG.error("Error getting current DLFileVersion of DLFileEntry " + dlFileEntry.getFileEntryId(), var4);
			return "";
		}
	}

	private String getThumbnailSrc(DLFileEntry dlFileEntry, DLFileVersion dlFileVersion, ThemeDisplay themeDisplay) {
		FileVersion fileVersion = null;
		FileEntry fileEntry = null;

		try {
			fileEntry = serviceTrackerBean.getDlAppService().getFileEntry(dlFileEntry.getFileEntryId());
			fileVersion = serviceTrackerBean.getDlAppService().getFileVersion(dlFileVersion.getFileVersionId());
			return DLUtil.getThumbnailSrc(fileEntry, fileVersion, (DLFileShortcut) null, themeDisplay);
		} catch (Exception var7) {
			LOG.error("Error getting thumbnail src for DLFileEntry " + dlFileEntry.getFileEntryId(), var7);
			return "";
		}
	}

	private String getPreviewURL(DLFileEntry dlFileEntry, ThemeDisplay themeDisplay) {
		try {
			DLFileVersion dlFileVersion = dlFileEntry.getFileVersion();
			return this.getPreviewURL(dlFileEntry, dlFileVersion, themeDisplay);
		} catch (Exception var4) {
			LOG.error("Error getting current DLFileVersion of DLFileEntry " + dlFileEntry.getFileEntryId(), var4);
			return "";
		}
	}

	private String getPreviewURL(DLFileEntry dlFileEntry, DLFileVersion dlFileVersion, ThemeDisplay themeDisplay) {
		FileVersion fileVersion = null;
		FileEntry fileEntry = null;

		try {
			fileEntry = serviceTrackerBean.getDlAppService().getFileEntry(dlFileEntry.getFileEntryId());
			fileVersion = serviceTrackerBean.getDlAppService().getFileVersion(dlFileVersion.getFileVersionId());
			return DLUtil.getPreviewURL(fileEntry, fileVersion, themeDisplay, "");
		} catch (Exception var7) {
			LOG.error("Error getting thumbnail src for DLFileEntry " + dlFileEntry.getFileEntryId(), var7);
			return "";
		}
	}

	public void handleFileUpload(FileUploadEvent event) {
		UploadedFile file = event.getFile();

		try {
			ServiceContext serviceContext = ScrumUtil.getServiceContext();
			long fileEntryId = this.createFile(serviceContext, file);
			this.createMapping(serviceContext, fileEntryId);
		} catch (DuplicateFileException var6) {
			FacesContext context = FacesContext.getCurrentInstance();
			FacesMessageUtil.addInfoMessage("uploadForm", context, "scrum-document-already-exists", file.getFileName());
			this.saveFileToReplace(file);
		} catch (Exception var7) {

ncrowds-workspace/modules/com.ncrowd.scrum.portlet/src/main/java/com/ncrowd/scrum/model/Document.java
package com.ncrowd.scrum.model;

import com.liferay.document.library.kernel.model.DLFileEntry;
import com.liferay.document.library.kernel.model.DLFileVersion;
import com.liferay.document.library.kernel.util.PDFProcessorUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.repository.model.FileEntry;
import com.liferay.portal.kernel.repository.model.FileVersion;
import com.ncrowd.scrum.bean.ServiceTrackerBean;
import com.ncrowd.scrum.util.ScrumUtil;

import java.io.IOException;
import java.io.InputStream;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.bean.ManagedProperty;

import org.primefaces.model.StreamedContent;

public class Document {
	private long documentId;
	private String title;
	private String description;
	private String version;
	private String mimeType;
	private long size;
	private String userName;
	private Date date;
	private String thumbnailSrc;
	private String previewSrc;
	private List<Document> oldVersions;
	private long mappingId;
	private Map<String, String> mimeTypeMapping;
	private static final Log LOG = LogFactoryUtil.getLog(Document.class);

	@ManagedProperty("#{trackerBean}")
	private ServiceTrackerBean serviceTrackerBean;

	public void setServiceTrackerBean(ServiceTrackerBean serviceTrackerBean) {
		this.serviceTrackerBean = serviceTrackerBean;
	}

	public Document() {
	}

	public Document(DLFileEntry dlFileEntry, String thumbnailSrc, String previewSrc, long mappingId) {
		this.documentId = dlFileEntry.getFileEntryId();
		this.title = dlFileEntry.getTitle();
		this.description = dlFileEntry.getDescription();
		this.version = dlFileEntry.getVersion();
		this.mimeType = dlFileEntry.getMimeType();
		this.size = dlFileEntry.getSize();
		this.userName = dlFileEntry.getUserName();
		this.date = dlFileEntry.getModifiedDate();
		this.thumbnailSrc = thumbnailSrc;
		this.previewSrc = previewSrc;
		this.mappingId = mappingId;
		this.mimeTypeMapping = this.fillMimeTypeMapping();
	}

	private Map<String, String> fillMimeTypeMapping() {
		return new HashMap<>();
	}

	public Document(DLFileVersion dlFileVersion, String thumbnailSrc, String previewSrc) {
		this.documentId = dlFileVersion.getFileEntryId();
		this.title = dlFileVersion.getTitle();
		this.description = dlFileVersion.getDescription();
		this.version = dlFileVersion.getVersion();
		this.mimeType = dlFileVersion.getMimeType();
		this.size = dlFileVersion.getSize();
		this.userName = dlFileVersion.getUserName();
		this.date = dlFileVersion.getModifiedDate();
		this.thumbnailSrc = thumbnailSrc;
		this.previewSrc = previewSrc;
		this.mappingId = 0L;
	}

	public long getDocumentId() {
		return this.documentId;
	}

	public String getDocumentIdString() {
		return String.valueOf(this.documentId);
	}

	public void setDocumentId(long documentId) {
		this.documentId = documentId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getMimeType() {
		return this.mimeType;
	}

	public String getMimeTypePretty() {
		String mapping = this.mimeTypeMapping.get(this.mimeType);
		return mapping != null ? mapping : this.mimeType;
	}

	public void setMimeType(String mimeType) {
		this.mimeType = mimeType;
	}

	public long getSize() {
		return this.size;
	}

	public String getSizeFormat() {
		if (this.size >= 1048576L) {
			return Math.round((float) this.size / 1048576.0F) + " MB";
		} else {
			return this.size >= 1024L ? Math.round((float) this.size / 1024.0F) + " KB" : this.size + " B";
		}
	}

	public void setSize(long size) {
		this.size = size;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getThumbnailSrc() {
		return this.thumbnailSrc;
	}

	public void setThumbnailSrc(String thumbnailSrc) {
		this.thumbnailSrc = thumbnailSrc;
	}

	public String getPreviewSrc() {
		return this.previewSrc;
	}

	public void setPreviewSrc(String previewSrc) {
		this.previewSrc = previewSrc;
	}

	public List<Document> getOldVersions() {
		return this.oldVersions;
	}

	public void setOldVersions(List<Document> oldVersions) {
		this.oldVersions = oldVersions;
	}

	public StreamedContent getFile() throws PortalException, IOException {
		DLFileEntry dlFileEntry = serviceTrackerBean.getDlFileService().fetchDLFileEntry(this.documentId);
		if (dlFileEntry != null) {
			InputStream stream = dlFileEntry.getContentStream();
			ScrumUtil.writeStreamToOutputStream(stream, this.title, this.mimeType);
		}

		return null;
	}

	public long getMappingId() {
		return this.mappingId;
	}

	public void setMappingId(long mappingId) {
		this.mappingId = mappingId;
	}

	public boolean isImage() {
		return this.mimeType.startsWith("image/") || !PDFProcessorUtil.isDocumentSupported(this.mimeType);
	}

	public boolean isMedia() {
		if (this.isImage()) {
			return false;
		} else if ("application/pdf".equals(this.mimeType)) {
			return true;
		} else {
			try {
				FileEntry fileEntry = serviceTrackerBean.getDlAppService().getFileEntry(this.documentId);
				FileVersion fileVersion = fileEntry.getFileVersion(this.version);
				if (PDFProcessorUtil.hasImages(fileVersion)) {
					return true;
				}
			} catch (Exception var3) {
				LOG.error("Error getting PDF preview of document " + this.documentId, var3);
			}

			return false;
		}
	}

	public boolean isPreviewable() {
		return this.isImage() || this.isMedia();
	}

	public String getPdfPreviewUrl() {
		return "application/pdf".equals(this.mimeType) ? this.previewSrc : this.previewSrc + "&targetExtension=pdf";
	}
}

ncrowds-workspace/modules/com.ncrowd.scrum.portlet/src/main/webapp/WEB-INF/views/burndown.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
    xmlns:ui="http://java.sun.com/jsf/facelets">
	
	<p:chart type="line" model="#{statsBean.burndownChart}" minY="0" animate="false" extender="scrum.util.extendPlot"
		seriesColors="FF0000" legendPosition="e" widgetVar="burndown" />
		
		
	<p:outputPanel rendered="#{prefBean.currentSprintId == 0}" layout="block">
		<h:outputText value="#{i18n['scrum-burndown-backlog']}" />
	</p:outputPanel>
	
</ui:composition>

ncrowds-workspace/modules/com.ncrowd.scrum.portlet/src/main/webapp/WEB-INF/views/documents.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsf/composite/composites"
	xmlns:portlet="http://java.sun.com/portlet_2_0">
					
   	<p:outputPanel id="filePanel" styleClass="scrumFieldset" layout="block">
   		<ui:fragment rendered="#{!task.new}">
   			<p:fieldset id="fileFieldset" legend="#{i18n['scrum-form-file-header']}"
    			toggleable="true" toggleSpeed="500" collapsed="#{prefBean.fileFieldsetHidden}">
    			
    			<p:ajax event="toggle" listener="#{prefBean.handleToggleFieldset}" />
				
				<h:form id="documentForm">
				            
				    <p:treeTable value="#{documentBean.documentTree}" var="document" style="margin-bottom: 25px;" emptyMessage="#{i18n['scrum-document-table-empty']}">
				        <f:facet name="header">
				            <h:outputText value="#{i18n['scrum-documents-header']}" />
				        </f:facet>
				  
				        <p:column styleClass="documentTitleColumn">
				            <f:facet name="header">
				            	<h:outputText value="#{i18n['scrum-documents-title']}" />
				            </f:facet>
				            <p:outputPanel styleClass="documentTitle" layout="block">
				            	<h:outputText value="#{document.title}" title="#{document.title}" />
				            </p:outputPanel>
				        </p:column>
				  
				        <p:column>
				            <f:facet name="header">
				            	<h:outputText value="#{i18n['scrum-documents-version']}" />
				            </f:facet>
				            <h:outputText value="#{document.version}" />
				        </p:column>
				        
				        <p:column>
				            <f:facet name="header">
				            	<h:outputText value="#{i18n['scrum-documents-preview']}" />
				            </f:facet>
				            
				            <p:lightBox rendered="#{document.image}" style="float: left">  
							    <h:outputLink value="#{document.previewSrc}" title="#{document.title}">
				        			<p:graphicImage styleClass="resizePreview" width="100px" url="#{document.thumbnailSrc}" />
							    </h:outputLink>
							</p:lightBox>
							
							<p:lightBox rendered="#{document.media}">  
							    <h:outputLink value="#" title="#{document.title}">  
							        <p:graphicImage styleClass="resizePreview" width="100px" url="#{document.thumbnailSrc}" />
							    </h:outputLink>
							    
							    	<portlet:resourceURL var="resourceURL" id="pdfPreview">
							    		<portlet:param name="fileEntryId" value="#{document.documentIdString}" />
							    		<portlet:param name="fileVersion" value="#{document.version}" />
							    	</portlet:resourceURL>
							  
							    <f:facet name="inline">
							        <p:media value="#{resourceURL}" player="pdf" width="500px" height="600px" />
							        <p:media value="#{document.pdfPreviewUrl}" player="pdf" width="500px" height="600px" />
							    </f:facet>
							</p:lightBox>
							
							<p:graphicImage rendered="#{!document.previewable}" width="100px" url="#{document.thumbnailSrc}" />
							
				        </p:column>
				  
				        <p:column>
				            <f:facet name="header">
				            	<h:outputText value="#{i18n['scrum-documents-mimetype']}" />
				            </f:facet>
				            <p:outputPanel styleClass="documentMimeType" layout="block">
				            	<h:outputText value="#{document.mimeType}" title="#{document.mimeType}" />
				            </p:outputPanel>
				        </p:column>
				  
				        <p:column>
				            <f:facet name="header">
				            	<h:outputText value="#{i18n['scrum-documents-size']}" />
				            </f:facet>
				            <h:outputText value="#{document.sizeFormat}" />
				        </p:column>
				  
				        <p:column>
				            <f:facet name="header">
				            	<h:outputText value="#{i18n['scrum-documents-date']}" />
				            </f:facet>
				            <h:outputText value="#{document.date}" />
				        </p:column>
				  
				        <p:column styleClass="documentActionsColumn">
				            
							<p:outputPanel layout="block" style="float: left;">
								<p:commandLink ajax="false" styleClass="downloadIcon" title="#{i18n['scrum-tooltip-download']}">
									<p:fileDownload value="#{documentBean.getFile(document.documentId,document.title,document.mimeType)}" />
								</p:commandLink>
							</p:outputPanel>
							
							<ui:fragment rendered="#{document.oldVersions != null}">
					            <p:outputPanel layout="block" style="float: left;">
						            <p:commandLink onclick="confirmation_#{document.documentId}.show()" styleClass="deleteDocumentIcon" title="#{i18n['scrum-tooltip-delete-document']}" />
						        </p:outputPanel>
						        
						        <p:confirmDialog id="confirmDialog" message="#{i18n.replace('scrum-documents-delete-confirm', document.title)}"
						        	header="#{i18n['scrum-documents-delete-header']}" severity="alert" widgetVar="confirmation_#{document.documentId}">
											
									<p:commandButton id="confirm" value="#{i18n['scrum-delete']}" actionListener="#{documentBean.deleteMappingFromTable(document.mappingId)}"
										update=":documentForm" onclick="confirmation_#{document.documentId}.hide();" oncomplete="scrum.util.toggleTreeRows();" />
									<p:commandButton id="decline" value="#{i18n['scrum-cancel']}" onclick="confirmation_#{document.documentId}.hide()" type="button" /> 
											
								</p:confirmDialog>
							</ui:fragment>
				        </p:column>
				    </p:treeTable>
				  
				</h:form>  
				
    			<h:form id="uploadForm" enctype="multipart/form-data">
    			
    				<p:messages autoUpdate="true" severity="info, error" for="uploadForm" />

					<p:outputPanel id="replaceFilePanel" layout="block" rendered="#{documentBean.fileToReplace != null}" autoUpdate="true">
						
						<p:outputPanel layout="block">
							<h:outputText value="#{i18n['scrum-documents-replace-info-existing']}" rendered="#{!documentBean.fileToReplace.alreadyAssigned}" />
							<h:outputText value="#{i18n['scrum-documents-replace-info']}" /><br />
						</p:outputPanel><br />
					
						<p:commandButton id="useExistingFile" value="#{i18n['scrum-documents-use-existing']}" actionListener="#{documentBean.useExistingFile}"
							rendered="#{!documentBean.fileToReplace.alreadyAssigned}" update=":documentForm uploadForm" oncomplete="scrum.util.toggleTreeRows();" />
					
						<p:commandButton id="replaceFile" value="#{i18n['scrum-documents-replace']}" actionListener="#{documentBean.replaceFile}"
							update=":documentForm uploadForm" oncomplete="scrum.util.toggleTreeRows();" />
							
						<p:commandButton id="keepFile" value="#{i18n['scrum-documents-keep']}" actionListener="#{documentBean.keepFile}"
							update=":documentForm uploadForm" oncomplete="scrum.util.toggleTreeRows();" />
						
						<p:commandButton id="cancelReplace" value="#{i18n['scrum-cancel']}" update=":documentForm uploadForm"
							oncomplete="scrum.util.toggleTreeRows();">
							<f:setPropertyActionListener value="#{null}" target="#{documentBean.fileToReplace}" />
						</p:commandButton>
					</p:outputPanel>
					
					<p:outputPanel rendered="#{documentBean.fileToReplace == null}" layout="block" styleClass="uploadHeader ui-widget-header ui-corner-top">
						<h:outputText value="#{i18n['scrum-documents-add']}" />
					</p:outputPanel>
					
				   	<p:fileUpload rendered="#{documentBean.fileToReplace == null}" id="uploadNew" fileUploadListener="#{documentBean.handleFileUpload}" mode="advanced"
				    	update=":documentForm uploadForm" oncomplete="scrum.util.toggleTreeRows();"
				    	label="#{i18n['scrum-documents-choose']}" cancelLabel="#{i18n['scrum-cancel']}" uploadLabel="#{i18n['scrum-documents-upload']}" />

				</h:form>
   			
    		</p:fieldset>
    	</ui:fragment>
   	</p:outputPanel>

	<script type="text/javascript">
		$(function() {scrum.util.toggleTreeRows();});
	</script>
</ui:composition>